[package]
name = "challenge_1brc"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
libc = {version = "0.2.155"}
algorithms = { git = "https://github.com/SuperioOne/algorithms.git" } 
